Верстка главной страницы и каталога
htmlacademy-htmlcss/1573711-device-34 pull request #2
Opened 2022-05-21 06:01 UTC by loonymax

Я решила оставить тег dl в первом слайдере, попробую сделать так, потому что получается семантичнее. Надеюсь, так тоже получится

2022-05-22 15:09 UTC, Pakistanka requested changes

2022-05-22 15:09 UTC, Pakistanka commented on catalog.html
> +        <ol class="cards-pagination">
Думаю, лучше будет ul, потому что ты используешь здесь тег списка как обертку, а не по прямому назначению

2022-05-22 15:09 UTC, Pakistanka commented on index.html
> +            <ol class="slider-paginator-list">
Думаю, лучше будет ul, потому что ты используешь здесь тег списка как обертку, а не по прямому назначению

2022-05-22 15:09 UTC, Pakistanka commented on catalog.html
> +      <a class="html-academy-link" href="">
Здесь разве не должна быть ссылка?

2022-05-22 15:09 UTC, Pakistanka commented on index.html
> +      <a class="header-catalog" href="#">
У вас по ТЗ должен быть реализован переход на страницу `catalog.html`.

Добавь, пожалуйста

2022-05-23 05:36 UTC, loonymax commented on index.html
> +      <a class="header-catalog" href="#">
У нас на макете вторая страница - это "Моноподы для селфи". Как раз этот пункт есть внутри выпадающего списка каталога товаров. Я думала его сделать там. Или пока для удобства пока сделать переход по этой ссылке?

2022-05-23 09:18 UTC, loonymax commented on index.html
> +      <a class="header-catalog" href="#">
Либо можно сделать чуть ниже, где идет перечисление товаров - у меня это список products-list. Там тоже есть "моноподы для селфи"

2022-05-23 14:43 UTC, Pakistanka commented on index.html
> +      <a class="header-catalog" href="#">
Окей, снимаю этот пункт.

2022-05-23 14:43 UTC, merged