Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/1573711-device-34 pull request #5
Opened 2022-06-02 09:06 UTC by loonymax

2022-06-04 07:27 UTC, Pakistanka requested changes
1. http://joxi.ru/82QX8NJC8Mg4bm - нужно убрать точечки и default отступы у всех списков

2022-06-04 07:27 UTC, Pakistanka commented on styles/style.css
>    font-size: 36px;
Нужно еще обнулить  default отступы у тега dd

2022-06-04 07:27 UTC, Pakistanka commented on styles/style.css
> +  margin-left: 505px;
Слишком большой margin-left. Скорее всего, где-то ошибка с сеткой

2022-06-04 07:47 UTC, loonymax commented on styles/style.css
> +  margin-left: 505px;
http://joxi.ru/52aGOj4Ul3X19r 
Я сделала вот это расстояние через margin-left, это неправильно? У меня еще вариант в голове: сделать обертку и оттолкнуть ее через margin-left: auto

2022-06-04 11:18 UTC, Pakistanka commented on styles/style.css
> +  margin-left: 505px;
Это неправильно. Лучше, если ты, например, сделаешь это через grid
`grid-templates-columns: repeat(3, 1fr);
grid-templates-rows: repeat(2, 1fr);`

Что-то типо того.  Это разметка для всего футера

2022-06-04 13:04 UTC, loonymax commented on styles/style.css
> +  margin-left: 505px;
У нас гриды по плану через раздел, я могу пока что оставить так, а на гридах переделать? Теорию как раз почитаю

2022-06-05 05:58 UTC, Pakistanka commented on styles/style.css
> +  margin-left: 505px;
Договорились

2022-06-05 10:01 UTC, merged