Микросетки
htmlacademy-htmlcss/1573711-device-34 pull request #6
Opened 2022-06-06 09:40 UTC by loonymax

2022-06-06 14:43 UTC, Pakistanka requested changes

2022-06-06 14:43 UTC, Pakistanka commented on styles/style.css
> +  margin-right: auto;
А зачем два раза вызывать один и тот же класс, с одним и тем же потомком.

Может лучше объединить?

2022-06-06 14:43 UTC, Pakistanka commented on styles/style.css
> +  flex-direction: column;
пока можно оставить, но у тебя не вертикальный слайдер, чтобы в колонку выставлять слайды

2022-06-06 14:43 UTC, Pakistanka commented on styles/style.css
> +
Лучше написать вот так
`.cards-title,
.cards-sort,
.cards-popular {
  margin: 0;
}
`

2022-06-07 07:42 UTC, loonymax commented on styles/style.css
> +  flex-direction: column;
http://joxi.ru/Vm6gMJ0S3dw7V2
Я выставляла в колонну вот эти элементы, и меняла у них очередность. Или это не верно?

2022-06-08 06:20 UTC, Pakistanka commented on styles/style.css
> +  flex-direction: column;
Верно. Я подумала, это к чему-то другому относится. Сорри

2022-06-08 15:29 UTC, loonymax commented on styles/style.css
> +  flex-direction: column;
У меня есть `.slider-wrapper` для слайдера и `.slider-features-wrapper` для блока с особенностями внутри слайдера. Так можно оставить или нейминг не очень?)

2022-06-09 04:12 UTC, Pakistanka commented on styles/style.css
> +  flex-direction: column;
Оставляй

2022-06-11 07:00 UTC, merged